version: "3.8"

services:
  web:
    build: ./docker/web
    container_name: pos-web
    ports:
      - "8088:80"
    volumes:
      - ./src/backend:/var/www
    environment:
      - DB_HOST=db
      - DB_NAME=pos
      - DB_USER=pos_user
      - DB_PASSWORD=pos_password
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - db
      - mongodb

  db:
    image: mysql:8.0
    container_name: pos-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pos
      MYSQL_USER: pos_user
      MYSQL_PASSWORD: pos_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:6.0
    container_name: pos-mongodb
    ports:
      - "27018:27017"   # host 27018 map ไป container 27017
    volumes:
      - mongo_data:/data/db

  phpmyadmin:
    image: phpmyadmin:5
    container_name: pos-phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=pos_user
      - PMA_PASSWORD=pos_password
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
  mongo_data:
